routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//

use App\Brand;
use App\Product;
use Illuminate\Http\Request;

Route::get('/', function () {
    $products = Product::with('categories.maincategory')->inRandomOrder()->paginate(12); // with('categories')->
    $products->load('photos.file');
    $products2 = Product::with('categories.maincategory')->latest()->paginate(12); // with('categories')->
    $products2->load('photos.file');
    $brands = Brand::with('photo.file')->get();
    return view('theme.page', compact('products', 'products2', 'brands'));
})->name('home');


Route::name('shop.')->prefix('shop')->group(function(){
    Route::get('/', 'ShopController@index');
    Route::get('/product/{product}', 'ShopController@showProduct')->name('product');
    Route::get('/tag/{tag}/products', 'ShopController@showProductByTag')->name('tag');
    Route::get('/brand/{brand}/products', 'ShopController@showProductByBrand')->name('brand');
    Route::get('/category/{category}', 'ShopController@categorize')->name('category');
});

Route::view('about', 'theme.about')->name('about');

Route::view('contact', 'theme.contact')->name('contact');


Route::name('cart.')->prefix('cart')->group(function(){
    Route::get('/', 'CartController@showCart');
    Route::get('/empty', 'CartController@forgetCart')->name('forget');
    Route::get('/{product}/{action}', 'CartController@cartAction')->name('actions');
});

Route::name('checkout.')->middleware('auth')->prefix('checkout')->group(function() {
    Route::get('/', 'CheckoutController@index')         ->name('makeorder');
    Route::get('/{order}', 'CheckoutController@show')   ->name('order');
    Route::put('/{order}', 'CheckoutController@update')   ->name('order.update');
    Route::post('/{order}/pay', 'CheckoutController@pay')->name('payment');
    Route::get('/payment/{payment}/pay', 'CheckoutController@bill')->name('pay');
});

Route::name('userarea.')->prefix('userarea')->middleware(['phone', 'auth', 'verified'])->group(function() {
    Route::get('/', 'UserAreaController@index');
    Route::get('/orders', 'UserAreaController@orders')->name('orders');
    Route::get('/invoices', 'UserAreaController@invoices')->name('invoices');
    Route::get('/invoices/{invoice}', 'UserAreaController@invoice')->name('invoices.show');
    Route::get('/payments', 'UserAreaController@payments')->name('payments');
    Route::get('/payments/{payment}', 'UserAreaController@payment')->name('payment');
    Route::get('/customer', 'UserAreaController@customer')->name('customer');
    Route::post('/customer', 'UserAreaController@store')->name('customercreate');
    Route::post('/customer/{customer}', 'UserAreaController@update')->name('customeredit');
    Route::get('/user/edit', 'UserController@edit')->name('user.edit');
    Route::put('/user/update', 'UserController@update')->name('user.update');
});

Route::prefix('phone')->name('phone.')->group(function() {
   Route::get('verify', 'SMSController@sendVerification')->name('verify');
   Route::post('verify', 'SMSController@verifyCode')->name('verify');
   Route::post('verify/resend', 'SMSController@resendVerification')->name('resend-verify');
});

Route::get('gallery/main-gallery', 'GalleryController@index')->name('gallery.index');

Route::get('gallery/{gallery}', 'GalleryController@show')->name('gallery.show');

Route::prefix('form')->name('form.')->group(function() {
   Route::get('/', 'FormController@index');
   Route::post('/', 'FormController@store')->name('store');
});

Route::match(['get', 'post'], 'verify_payment/{gateway}', [
    'uses' => 'GateWaysController@verify',
    'as'   => 'verifypayment',
]);

Route::prefix('sitemaps')->name('sitemaps.')->group(function(){
    Route::get('/sitemaps.xml', 'SitemapsController@index');
    Route::get('/sitemap-{sitemap}.xml', 'SitemapsController@show')->name('show');
});

Auth::routes(['verify' => true]);

Route::prefix('auth/password')->name('auth.passwords.')->group(function(){
    Route::view('reset', 'auth.passwords.reset')->name('create');
    Route::post('reset/{type}', 'PasswordResetController@store')->name('store');
    Route::put('reset', 'PasswordResetController@update')->name('update');
    Route::get('change/{token}', 'PasswordResetController@show')->name('confirm.form');
    Route::post('sms/resend/{token}', 'PasswordResetController@resendSms')->name('resendsms');
    // Route::post('confirm/phone/{phone}', 'PasswordResetController@phoneVerify')->name('confirm.phone');
});

Route::get('search', 'SearchController@index')->name('pages.search');

resources/views/theme/contact.blade.php
@extends('layout.default')
@section('head')
<title>{{ setting('site.company-name') }} - تماس با ما</title>
@endsection
@section('content')
    <header>
        @include('theme.header')
    </header>
    <div class="col-12 content">
        <div class="col-12 mb-4 section scroll-animations">
            <div class="title-row float-left animated fadeInRight">
                <h4 class="title">تماس با ما</h4>
                <span class="underline col-sm-2 offset-sm-5 col-8 offset-2 mt-3"></span>
            </div>
            <form class="col-md-6 offset-md-3 col-12 offset-0 float-left" action="{{ route('form.store') }}" method="post">
                @csrf
                <div class="input-group float-right col-lg-6 col-md-12 mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1"><i class="fa fa-user"></i></span>
                    </div>
                    <input type="text" name="name" required class="form-control" placeholder="نام و نام خانوادگی">
                </div>
                <div class="input-group float-right col-lg-6 col-md-12 mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1"><i class="fa fa-phone"></i></span>
                    </div>
                    <input type="text" name="phone" required class="form-control" placeholder="شماره تماس">
                </div>
                <div class="input-group float-right col-lg-6 col-md-12 mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1"><i class="fa fa-envelope"></i></span>
                    </div>
                    <input type="text" name="email" class="form-control" placeholder="ایمیل">
                </div>
                <div class="input-group float-right col-lg-6 col-md-12 mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">حوزه فعالیت</span>
                    </div>
                   <select required class="form-control" name="bussiness">
                       <option selected value="مصرف کننده">مصرف کننده</option>
                       <option value="فروشنده محصولات">فروشنده محصولات</option>
                       <option value="بازاریاب">بازاریاب</option>
                       <option value="آرایشگر">آرایشگر</option>
                       <option value="سایر">سایر</option>
                   </select>
                </div>
                <div class="input-group float-right col-lg-6 col-md-12 mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">چگونه با ما آشنا شدید</span>
                    </div>
                   <select required class="form-control" name="knowing">
                       <option selected value="تبلیغات">تبلیغات</option>
                       <option value="استفاده از محصولات ما">استفاده از محصولات ما</option>
                       <option value="شبکه های اجتماعی">شبکه های اجتماعی</option>
                       <option value="با معرفی دوستان و آشنایان">با معرفی دوستان و آشنایان</option>
                       <option value="ارتباط با شرکت">ارتباط با شرکت</option>
                   </select>
                </div>
                <div class="input-group float-right col-12 mb-3">
                    <textarea required minlength="10" maxlength="700" class="form-control float-right" name="question" id="question" cols="30" rows="10" placeholder="سوال (جهت راهنمایی دقیق تر و بهتر در امر مشاوره لطفا سوال خود را با ذکر جزئیات ، کامل بپرسید) "></textarea>
                    <div class="col-12 mt-3 p-0 float-right">
                        <button type="submit" class="btn btn-primary">ارسال</button>
                    </div>
                </div>
            </form>
        </div>
        <div class="col-12 mb-4 section scroll-animations contactus-section">
			<div class="contact-datas">
				<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12"><p class="titlec">آدرس</p><p>{{ setting('site.address') }}</p></div>
				<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12"><p class="titlec">شماره تماس</p><p class="phone">{!! setting('site.phone') !!}</p></div>
                <div class="col-lg-6 col-md-6 col-sm-6 col-xs-12"><p class="titlec">ایمیل</p><p>{{ setting('site.email') }}</p></div>
				<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12"><p class="titlec">ساعات کاری</p><div class="working-date"><p class="days">{{ setting('site.workdays') }}</p><p class="timed">{{ setting('site.workhours') }} </p></div></div>
			</div>
			<div class="backmap">
				<div>
				<p><i class="fa fa-map-marker fa-3x"></i><span>{{ setting('site.company-name') }}<br>{{ setting('site.company-subtitle') }}</span></p>
				<p class="ads">{{ setting('site.address') }}</p>
				<a class="btn btndir" target="_blank" href="{{ setting('site.googlemaps') }}">دریافت مسیر ها<i class="fa fa-angle-right"></i></a>
				</div>
			</div>
		</div>
    </div>
    @include('theme.components.footer')
@endsection
@section('script')
    <script src="{{ asset('js/app.js') }}"></script>
@endsection

resources/views/theme/form.blade.php
@extends('layout.default')
@section('head')
<title>{{ setting('site.company-name') }} - فرم مشاوره</title>
@endsection
@section('content')
    <header>
        @include('theme.header')
    </header>
    <div class="col-12 content">
        <div class="col-12 mb-4 section scroll-animations">
            <div class="title-row float-left animated fadeInRight">
                <h2 class="title">فرم مشاوره</h2>
                <span class="underline col-sm-2 offset-sm-5 col-8 offset-2 mt-3"></span>
            </div>
            <p class="col-md-8 offset-md-2 col-12 offset-0 text-center float-left">
            دوست عزیز سلام.
<br>
جهت مشاوره در امر زیبائی و سلامت مو و پوست سر ، لطفا سوال خود را پس از تکمیل موارد ذیل مطرح فرمائید.
            </p>
            <form class="col-md-6 offset-md-3 col-12 offset-0 float-left" action="{{ route('form.store') }}" method="post">
                @csrf
                <div class="input-group float-right col-lg-6 col-md-12 mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1"><i class="fa fa-user"></i></span>
                    </div>
                    <input type="text" name="name" required class="form-control" placeholder="نام و نام خانوادگی">
                </div>
                <div class="input-group float-right col-lg-6 col-md-12 mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1"><i class="fa fa-phone"></i></span>
                    </div>
                    <input type="text" name="phone" required class="form-control" placeholder="شماره تماس">
                </div>
                <div class="input-group float-right col-lg-6 col-md-12 mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1"><i class="fa fa-envelope"></i></span>
                    </div>
                    <input type="text" name="email" class="form-control" placeholder="ایمیل">
                </div>
                <div class="input-group float-right col-lg-6 col-md-12 mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">حوزه فعالیت</span>
                    </div>
                   <select required class="form-control" name="bussiness">
                       <option selected value="مصرف کننده">مصرف کننده</option>
                       <option value="فروشنده محصولات">فروشنده محصولات</option>
                       <option value="بازاریاب">بازاریاب</option>
                       <option value="آرایشگر">آرایشگر</option>
                       <option value="سایر">سایر</option>
                   </select>
                </div>
                <div class="input-group float-right col-lg-6 col-md-12 mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text" id="basic-addon1">چگونه با ما آشنا شدید</span>
                    </div>
                   <select required class="form-control" name="knowing">
                       <option selected value="تبلیغات">تبلیغات</option>
                       <option value="استفاده از محصولات ما">استفاده از محصولات ما</option>
                       <option value="شبکه های اجتماعی">شبکه های اجتماعی</option>
                       <option value="با معرفی دوستان و آشنایان">با معرفی دوستان و آشنایان</option>
                       <option value="ارتباط با شرکت">ارتباط با شرکت</option>
                   </select>
                </div>
                <div class="input-group float-right col-12 mb-3">
                    <textarea required minlength="10" maxlength="700" class="form-control float-right" name="question" id="question" cols="30" rows="10" placeholder="سوال (جهت راهنمایی دقیق تر و بهتر در امر مشاوره لطفا سوال خود را با ذکر جزئیات ، کامل بپرسید) "></textarea>
                    <div class="col-12 mt-3 p-0 float-right">
                        <button type="submit" class="btn btn-primary">ارسال</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    @include('theme.components.footer')
@endsection
@section('script')
    <script src="{{ asset('js/app.js') }}"></script>
@endsection

resources/views/theme/gallery.blade.php
@extends('layout.default')
@section('head')
<title>{{ setting('site.company-name') }} - {{ $gallery->title }}</title>
<link rel="stylesheet" href="{{ asset('css/animate.css') }}">
@endsection
@section('content')
<header>
    @include('theme.header')
</header>
<div class="col-12 content">
    <div class="title-row float-left animated fadeInRight mt-3 mb-5">
        <h4 class="title">{{ $gallery->title }}</h4>
        <span class="underline col-sm-2 offset-sm-5 col-8 offset-2 mt-3"></span>
    </div>
        <div class="gallery-container col-12 mb-5">
            @foreach ($gallery->items as $item)
            @if($item->url)<a href="{{ $item->url }}">@endif
            <div class="col-md-2 col-6 float-left text-center">
                <img class="float-left h-auto col-12" src="{{ asset($item->file->path) }}" alt="{{ $item->title }} - روبیوتی">
                <div class="text-dark">
                    <p class="title">{{ $item->title }}</p>
                    <p class="persian">{{ $item->description }}</p>
                </div>
            </div>
            @if($item->url)</a>@endif
            @endforeach
        </div>
    </div>
</div>
@endsection

resources/views/theme/header.blade.php
@php
    $cart = \Session::get('cart', null);
@endphp
<div class="topbar">
    <div class="col-md-6 col-12">
        <p><i class="fa fa-phone"></i>{!! setting('header.phone') !!}</p>
        <p><i class="fa fa-envelope-open-o"></i><a href="mailto:{{ setting('site.email') }}">{{ setting('site.email') }}</a></p>
        <ul class="socialmedia">
            {!! setting('header.socialmenu') !!}
        </ul>
    </div>
    <div class="col-md-6 col-12"></div>
</div>
<div class="navbar">
    <div class="col-md-2 col-4 logo"><a href="{{ route('home') }}"><img src="{{ asset(setting('site.logo')) }}" alt="Robeauty"></a></div>
    <div class="col-lg-6 offset-lg-1 col-md-7 offset-md-1 col-12 offset-0 menu">
        <nav class="main-menu">
            <ul>
                <li><a href="{{ route('home') }}">صفحه اصلی</a></li>
                <li><a href="{{ route('shop.') }}">فروشگاه</a></li>
                {{-- <li><a href="/cosmetics">محصولات آرایشی</a></li> --}}
                <li><a href="{{ asset('gallery/main-gallery') }}">گالری شرکت</a></li>
                <li><a href="{{ route('gallery.show', ['gallery' => 'گالری-محصولات']) }}">تصاویر محصولات</a></li>
                <li><a href="{{ route('about') }}">درباره ما</a></li>
                <li><a href="{{ route('contact') }}">تماس با ما</a></li>
                <li><a id="search-toggle" href="{{ route('pages.search') }}">جستجو <i class="fa fa-search mr-2"></i></a></li>
            </ul>
        </nav>
    </div>
    <div class="col-md-3 col-8 control-panel">
        @guest
        <a href="{{ route('register') }}"><i class="fa fa-user fa-2x"></i><span class="d-sm-inline d-none">عضویت</span></a>
        <a href="{{ route('login') }}"><i class="fa fa-lock fa-2x"></i><span class="d-sm-inline d-none">ورود</span></a>
        @else
        <a href="{{ route('userarea.') }}"><i class="fa fa-user fa-2x"></i><span class="d-sm-inline d-none">{{ auth()->user()->name }} - ناحیه کاربری</span></a>
        @endguest
        <div class="mini-cart" data-cart="{{ route('cart.') }}" data-main="{{ asset('/') }}" data-product={{ route('shop.product', ['product' => 'productId']) }}>
            <i class="fa fa-shopping-bag fa-2x"></i>
            <span class="d-sm-inline d-none">سبد خرید</span>
            <span class="badge badge-pill badge-light">{{ ($cart) ? count($cart->items ): 0 }}</span>
            <div class="flow-cart">
                @if ($cart && $cart->items)
                    @foreach ($cart->items as $item)
                    <div class="cart-item p-3">
                        @if ($item['item']->photo)
                            <img src="{{ $item['item']->photo }}" alt="">
                        @endif
                        <p class="text-right">
                            <a href="{{ route('shop.product', ['product' => $item['item']->slug]) }}">
                            {{ $item['item']->title }}({{ $item['quantity'] }}x)
                            <br>
                            قیمت واحد : {{ number_format($item['item']->price) }} تومان
                            <b>مجموع: {{ number_format($item['price']) }} تومان</b>
                            </a>
                        </p>
                    </div>
                    @endforeach
                @endif
                <a class="btn btn-sm btn-dark float-left m-3" href="{{ route('cart.') }}">مشاهده سبد <i class="fa fa-shopping-bag fa-2x"></i></a>
            </div>
        </div>
        <div id="openmenu" class="btn btn-light m-0 mr-4 d-sm-none d-block"><i class="fa fa-2x fa-bars"></i></div>
    </div>
</div>

resources/views/theme/page.blade.php
@extends('layout.default')
@section('head')
<title>{{ setting('site.title') }}</title>
@endsection
@section('content')
    <header>
        @include('theme.header')
        @include('theme.components.slider')
    </header>
    <div class="col-12 content">
        <div class="col-12 section banner-section scroll-animations">
            <a href="{{ setting('mainpage.banner1.url') }}">
                <div class="col-md-3 col-12 banner">
                    <div class="card animated" data-animation="fadeInLeft">
                        <img src="{{ setting('mainpage.banner1') }}" alt="">
                    </div>
                </div>
            </a>
            <a href="{{ setting('mainpage.banner2.url') }}">
                <div class="col-md-6 col-12 banner">
                    <div class="card-full animated" data-animation="fadeInUp">
                        <img src="{{ setting('mainpage.banner2') }}" alt="">
                    </div>
                </div>
            </a>
            <a href="{{ setting('mainpage.banner3.url') }}">
                <div class="col-md-3 col-12 banner">
                    <div class="card animated" data-animation="fadeInRight">
                        <img src="{{ setting('mainpage.banner3') }}" alt="">
                    </div>
                </div>
            </a>
        </div>
        <div class="col-12 mb-4 section scroll-animations">
            <div class="title-row float-left animated" data-animation="fadeIn slow delay-1s">
                <h4 class="title">پیشنهادات ویژه</h4>
                <span class="underline col-sm-2 offset-sm-5 col-8 offset-2 mt-3"></span>
            </div>
            <div class="swiper-container productslider psl-2 col-12 mt-3 float-left animated" data-animation="slideInRight fast">
                <div class="swiper-wrapper">
                    @foreach ($products as $product)
                    <div class="swiper-slide">
                        <div class="cover">
                            @if (count($product->photos) > 0)
                                <img src="{{ asset($product->photos[0]->file->path) }}" alt="">
                            @endif
                        </div>
                        <div class="info">
                            <h3 class="book-title">{{ $product->title }}</h3>
                            <p class="book-subtitle">{{ $product->short_description }}</p>
                            <p>{{ number_format($product->price) }} تومان</p>
                            <div class="generes">
                                @foreach ($product->categories as $category)
                                    <a href="#" class="badge badge-secondary badge-pill">{{ $category->name }}</a>
                                @endforeach
                            </div>
                            <div class="generes">
                                <a href="{{ route('shop.product', ['product' => $product->slug]) }}" class="btn btn-secondary float-left">مشاهده</a>
                                <a class="btn btn-secondary float-left" href="{{ route('cart.actions', ['product' => $product->id, 'action' => 'add']) }}"
                                class="btn"><i class="fa fa-shopping-cart"></i></a>
                            </div>
                        </div>
                    </div>
                    @endforeach
                </div>
                <!-- Add Pagination -->
                <div class="swiper-button-prev"><i class="fa fa-3x fa-angle-left"></i></div>
                <div class="swiper-button-next"><i class="fa fa-3x fa-angle-right"></i></div>
            </div>
        </div>
        <div class="col-12 mb-4 section">
            <div class="title-row float-left">
                <h4 class="title">محصولات جدید</h4>
                <span class="underline col-sm-2 offset-sm-5 col-8 offset-2 mt-3"></span>
            </div>
            <div class="swiper-container productslider psl-0 col-12 mt-3 float-left">
                <div class="swiper-wrapper">
                    @foreach ($products2 as $product)
                    <div class="swiper-slide">
                        <div class="cover">
                            @if (count($product->photos) > 0)
                                <img src="{{ asset($product->photos[0]->file->path) }}" alt="">
                            @endif
                        </div>
                        <div class="info">
                            <a href="{{ route('shop.product', ['product' => $product->slug]) }}"><h3 class="book-title">{{ $product->title }}</h3></a>
                            <p class="book-subtitle">{{ $product->short_description }}</p>
                            <p>{{ number_format($product->price) }} تومان</p>
                            <div class="generes">
                            @foreach ($product->categories as $category)
                                <a href="#" class="badge badge-secondary badge-pill">{{ $category->name }}</a>
                            @endforeach
                            </div>
                            <div class="generes">
                                <a href="{{ route('shop.product', ['product' => $product->slug]) }}" class="btn btn-secondary float-left">مشاهده</a>
                                <a class="btn btn-secondary float-left" href="{{ route('cart.actions', ['product' => $product->id, 'action' => 'add']) }}"
                                class="btn"><i class="fa fa-shopping-cart"></i></a>
                            </div>
                        </div>
                    </div>
                    @endforeach
                </div>
                <!-- Add Pagination -->
                <div class="swiper-button-prev"><i class="fa fa-3x fa-angle-left"></i></div>
                <div class="swiper-button-next"><i class="fa fa-3x fa-angle-right"></i></div>
            </div>
        </div>
        <div class="col-12 mb-4 section">
            <div class="title-row float-left">
                <h4 class="title">برند ها</h4>
                <span class="underline col-sm-2 offset-sm-5 col-8 offset-2 mt-3"></span>
            </div>
            <div class="swiper-container brandslider psl-3 col-12 mt-3 float-left">
                <div class="swiper-wrapper">
                    @foreach ($brands as $brand)
                        <div class="swiper-slide">
                            <a href="{{ route('shop.brand', ['brand' => $brand->name]) }}">
                            <div class="cover">
                                <img src="{{ asset($brand->photo->file->path) }}" alt="">
                            </div>
                            </a>
                        </div>
                    @endforeach
                </div>
                <!-- Add Pagination -->
                <div class="swiper-button-prev"><i class="fa fa-3x fa-angle-left"></i></div>
                <div class="swiper-button-next"><i class="fa fa-3x fa-angle-right"></i></div>
            </div>
        </div>
    </div>
    @include('theme.components.footer')
@endsection
@section('script')
    <script src="{{ asset('js/app.js') }}"></script>
    <script>
    var mySwiper = new Swiper.default('#slider', {
        slidesPerView: 1,
        spaceBetween: 0,
        loop: true,
        pagination: {
            el: '.swiper-pagination',
            clickable: true,
        },
        navigation: {
            nextEl: '#slider > .swiper-button-next',
            prevEl: '#slider > .swiper-button-prev',
        },
        autoplay: {
            delay: 5000,
            disableOnInteraction: false,
        }
    });
    var swiper0 = new Swiper.default('.psl-0', {
        slidesPerView: 4,
        spaceBetween: 10,
        breakpoints: {
            320: {
                slidesPerView: 1,
                spaceBetween: 20,
            },
            500: {
                slidesPerView: 2,
                spaceBetween: 20,
            },
            768: {
                slidesPerView: 5,
                spaceBetween: 20,
            },
            2560: {
                slidesPerView: 6,
                spaceBetween: 40
            }
        },
        navigation: {
            nextEl: '.psl-0 > .swiper-button-next',
            prevEl: '.psl-0 > .swiper-button-prev',
        },
    });
    var swiper1 = new Swiper.default('.psl-1', {
        slidesPerView: 4,
        spaceBetween: 10,
        breakpoints: {
            320: {
                slidesPerView: 1,
                spaceBetween: 20,
            },
            500: {
                slidesPerView: 2,
                spaceBetween: 20,
            },
            768: {
                slidesPerView: 5,
                spaceBetween: 20,
            },
            2560: {
                slidesPerView: 6,
                spaceBetween: 40
            }
        },
        navigation: {
            nextEl: '.psl-1 > .swiper-button-next',
            prevEl: '.psl-1 > .swiper-button-prev',
        },
    });
    var swiper2 = new Swiper.default('.psl-2', {
        slidesPerView: 4,
        spaceBetween: 10,
        breakpoints: {
            320: {
                slidesPerView: 1,
                spaceBetween: 20,
            },
            500: {
                slidesPerView: 2,
                spaceBetween: 20,
            },
            768: {
                slidesPerView: 5,
                spaceBetween: 20,
            },
            2560: {
                slidesPerView: 6,
                spaceBetween: 40
            }
        },
        navigation: {
            nextEl: '.psl-2 > .swiper-button-next',
            prevEl: '.psl-2 > .swiper-button-prev',
        },
    });
    var swiper3 = new Swiper.default('.psl-3', {
        slidesPerView: 4,
        spaceBetween: 10,
        breakpoints: {
            320: {
                slidesPerView: 1,
                spaceBetween: 20,
            },
            500: {
                slidesPerView: 2,
                spaceBetween: 20,
            },
            768: {
                slidesPerView: 4,
                spaceBetween: 20,
            },
            2560: {
                slidesPerView: 4,
                spaceBetween: 40
            }
        },
        navigation: {
            nextEl: '.psl-3 > .swiper-button-next',
            prevEl: '.psl-3 > .swiper-button-prev',
        },
    }); </script>
@endsection

resources/views/theme/search.blade.php
@extends('layout.shop')

@section('head')
<title>@if($query) جستجوی "{{ $query }}" @else جستجو @endif| {{ setting('site.title') }}</title>
@endsection

@section('breadcrumb')
<li class="breadcrumb-item active" aria-current="page">@if($query) جستجوی "{{ $query }}" @else جستجو @endif</li>
@endsection
@section('shop-content')
    <div class="col-md-10 offset-md-1 col-12 float-left shopbar p-3 pt-0">
        <form method="GET" @if (! $query) style="height:400px;" @endif class="col-12 float-left p-3" action="{{ route('pages.search') }}">
            <div class="col-md-4 col-12 float-right input-group px-0">
                <input minlength="3" maxlength="80" type="text" name="query" id="query" value="{{ old('query') ?: $query_value }}" class="form-control">
                <div class="input-group-prepend">
                    <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i></button>
                </div>
            </div>
        </form>
        @if ($query)
            <div id="react-product-section" data-target="{{ $target_url }}"></div>
        @endif
    </div>
@endsection
@section('scriptcode')
<script>
var VisitProduct  = "{{ route('shop.product', ['product' => 'slug']) }}";
var VisitCategory = "{{ route('shop.category', ['category' => 'categoryName']) }}";
var CartAction = "{{ route('cart.actions', ['product' => 'productId', 'action' => 'actionName']) }}";
var Asset      = "{{ asset('/') }}";
</script>
<script src="{{ asset('js/products.js') }}"></script>
@endsection