routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//

use App\Brand;
use App\Product;
use Illuminate\Http\Request;

Route::get('/', function () {
    $products = Product::with('categories.maincategory')->inRandomOrder()->paginate(12); // with('categories')->
    $products->load('photos.file');
    $products2 = Product::with('categories.maincategory')->latest()->paginate(12); // with('categories')->
    $products2->load('photos.file');
    $brands = Brand::with('photo.file')->get();
    return view('theme.page', compact('products', 'products2', 'brands'));
})->name('home');


Route::name('shop.')->prefix('shop')->group(function(){
    Route::get('/', 'ShopController@index');
    Route::get('/product/{product}', 'ShopController@showProduct')->name('product');
    Route::get('/tag/{tag}/products', 'ShopController@showProductByTag')->name('tag');
    Route::get('/brand/{brand}/products', 'ShopController@showProductByBrand')->name('brand');
    Route::get('/category/{category}', 'ShopController@categorize')->name('category');
});

Route::view('about', 'theme.about')->name('about');

Route::view('contact', 'theme.contact')->name('contact');


Route::name('cart.')->prefix('cart')->group(function(){
    Route::get('/', 'CartController@showCart');
    Route::get('/empty', 'CartController@forgetCart')->name('forget');
    Route::get('/{product}/{action}', 'CartController@cartAction')->name('actions');
});

Route::name('checkout.')->middleware('auth')->prefix('checkout')->group(function() {
    Route::get('/', 'CheckoutController@index')         ->name('makeorder');
    Route::get('/{order}', 'CheckoutController@show')   ->name('order');
    Route::put('/{order}', 'CheckoutController@update')   ->name('order.update');
    Route::post('/{order}/pay', 'CheckoutController@pay')->name('payment');
    Route::get('/payment/{payment}/pay', 'CheckoutController@bill')->name('pay');
});

Route::name('userarea.')->prefix('userarea')->middleware(['phone', 'auth', 'verified'])->group(function() {
    Route::get('/', 'UserAreaController@index');
    Route::get('/orders', 'UserAreaController@orders')->name('orders');
    Route::get('/invoices', 'UserAreaController@invoices')->name('invoices');
    Route::get('/invoices/{invoice}', 'UserAreaController@invoice')->name('invoices.show');
    Route::get('/payments', 'UserAreaController@payments')->name('payments');
    Route::get('/payments/{payment}', 'UserAreaController@payment')->name('payment');
    Route::get('/customer', 'UserAreaController@customer')->name('customer');
    Route::post('/customer', 'UserAreaController@store')->name('customercreate');
    Route::post('/customer/{customer}', 'UserAreaController@update')->name('customeredit');
    Route::get('/user/edit', 'UserController@edit')->name('user.edit');
    Route::put('/user/update', 'UserController@update')->name('user.update');
});

Route::prefix('phone')->name('phone.')->group(function() {
   Route::get('verify', 'SMSController@sendVerification')->name('verify');
   Route::post('verify', 'SMSController@verifyCode')->name('verify');
   Route::post('verify/resend', 'SMSController@resendVerification')->name('resend-verify');
});

Route::get('gallery/main-gallery', 'GalleryController@index')->name('gallery.index');

Route::get('gallery/{gallery}', 'GalleryController@show')->name('gallery.show');

Route::prefix('form')->name('form.')->group(function() {
   Route::get('/', 'FormController@index');
   Route::post('/', 'FormController@store')->name('store');
});

Route::match(['get', 'post'], 'verify_payment/{gateway}', [
    'uses' => 'GateWaysController@verify',
    'as'   => 'verifypayment',
]);

Route::prefix('sitemaps')->name('sitemaps.')->group(function(){
    Route::get('/sitemaps.xml', 'SitemapsController@index');
    Route::get('/sitemap-{sitemap}.xml', 'SitemapsController@show')->name('show');
});

Auth::routes(['verify' => true]);

Route::prefix('auth/password')->name('auth.passwords.')->group(function(){
    Route::view('reset', 'auth.passwords.reset')->name('create');
    Route::post('reset/{type}', 'PasswordResetController@store')->name('store');
    Route::put('reset', 'PasswordResetController@update')->name('update');
    Route::get('change/{token}', 'PasswordResetController@show')->name('confirm.form');
    Route::post('sms/resend/{token}', 'PasswordResetController@resendSms')->name('resendsms');
    // Route::post('confirm/phone/{phone}', 'PasswordResetController@phoneVerify')->name('confirm.phone');
});

Route::get('search', 'SearchController@index')->name('pages.search');

resources/views/layout/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    @yield('head')
    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body class='body-register'>
    <div class='login-page-container'>
        <div class='yield-container'>
            @yield('content')
        </div>
    </div>
    <script src="{{ asset('js/app.js') }}"></script>
    @yield('script')
</body>
</html>

resources/views/layout/app.last.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    @yield('head')
    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    روبیوتی
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">ورود</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">ثبت نام</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layout/default.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="shortcut icon" href="{{ asset('favicon.ico') }}" type="image/x-icon">
    
    <link rel="stylesheet" href="{{ asset('css/app.css') }}">
    <link rel="stylesheet" href="{{ asset('css/animate.css') }}">
    <style>
        .alert {
            font-family: Iransans;
        }
        .closedaddy {
            float: left;
        }
        .closedaddy:hover {
            cursor: pointer;
        }
    </style>
    @yield('head')
</head>
<body class="no-sc">
    @if (session()->has('flash_message'))
        <div class="col-12 float-left text-right alert alert-{{ session('flash_message.level') == 'error' ? 'danger' : session('flash_message.level') }}">{{ session('flash_message.title') }} : {!! session('flash_message.message') !!} <i class="closedaddy fa fa-times"></i></div>
    @endif
    @if ($errors->any())
        @foreach ($errors->all() as $err)
            <div class="col-12 float-left m-0 text-right alert alert-danger">{{ $err }} <i class="closedaddy fa fa-times"></i></div>
        @endforeach
    @endif
    @yield('content')
    @yield('script')
    <script>
        $('.closedaddy').click(function() { $(this).parent().slideUp() })
    </script>
</body>
</html>

resources/views/layout/shop.blade.php
@extends('layout.default')

@section('content')
<header>@include('theme.header')</header>
<div class="content shop" style="text-align:left;">
    <nav class="breadcrumb-holder col-12 float-left p-3" aria-label="breadcrumb">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ route('home') }}">خانه</a></li>
            @yield('breadcrumb')
        </ol>
    </nav>
    @yield('shop-content')
</div>
@include('theme.components.footer')
@endsection

@section('script')
    <script src="{{ asset('js/app.js') }}"></script>
    @yield('scriptcode')
@endsection

resources/views/layout/userarea.blade.php
@extends('layout.default')

@section('content')
<header>
    @include('theme.header')
</header>
<div class="content col-12 p-3 userarea">
    <div class="title-row float-left">
        <h4 class="title">حساب کاربری من</h4>
        <span class="underline col-sm-2 offset-sm-5 col-8 offset-2 mt-3"></span>
    </div>
    <div class="account col-12 float-left">
        <div class="col-md-3 col-12 p-0 account-menu">
            <ul>
                <li><a href="{{ route('userarea.') }}"><i class="fa fa-dashboard"></i>داشبورد</a></li>
                <li><a href="{{ route('userarea.orders') }}"><i class="fa fa-cart-arrow-down"></i>سفارشات</a></li>
                <li><a href="{{ route('userarea.customer') }}"><i class="fa fa-map-marker"></i>اطلاعات ارسال</a></li>
                <li><a href="{{ route('userarea.invoices') }}"><i class="fa fa-invoice"></i>رسید ها</a></li>
                <li><a href="{{ route('userarea.payments') }}"><i class="fa fa-credit-card"></i>پرداختی ها</a></li>
                <li><a href="{{ route('userarea.user.edit') }}"><i class="fa fa-user"></i>اطلاعات حساب کاربری</a></li>
                <li>
                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                    @csrf
                    </form>
                    <a href="#" id="logouter"><i class="fa fa-sign-out"></i>خروج</a>
                </li>
            </ul>
        </div>
        <div class="col-md-9 col-12 p-3 account-content">
            @yield('dashboardcontent')
        </div>
    </div>
</div>
@include('theme.components.footer')
<script src="{{ asset('js/app.js') }}"></script>
@endsection