routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//

use App\Brand;
use App\Product;
use Illuminate\Http\Request;

Route::get('/', function () {
    $products = Product::with('categories.maincategory')->inRandomOrder()->paginate(12); // with('categories')->
    $products->load('photos.file');
    $products2 = Product::with('categories.maincategory')->latest()->paginate(12); // with('categories')->
    $products2->load('photos.file');
    $brands = Brand::with('photo.file')->get();
    return view('theme.page', compact('products', 'products2', 'brands'));
})->name('home');


Route::name('shop.')->prefix('shop')->group(function(){
    Route::get('/', 'ShopController@index');
    Route::get('/product/{product}', 'ShopController@showProduct')->name('product');
    Route::get('/tag/{tag}/products', 'ShopController@showProductByTag')->name('tag');
    Route::get('/brand/{brand}/products', 'ShopController@showProductByBrand')->name('brand');
    Route::get('/category/{category}', 'ShopController@categorize')->name('category');
});

Route::view('about', 'theme.about')->name('about');

Route::view('contact', 'theme.contact')->name('contact');


Route::name('cart.')->prefix('cart')->group(function(){
    Route::get('/', 'CartController@showCart');
    Route::get('/empty', 'CartController@forgetCart')->name('forget');
    Route::get('/{product}/{action}', 'CartController@cartAction')->name('actions');
});

Route::name('checkout.')->middleware('auth')->prefix('checkout')->group(function() {
    Route::get('/', 'CheckoutController@index')         ->name('makeorder');
    Route::get('/{order}', 'CheckoutController@show')   ->name('order');
    Route::put('/{order}', 'CheckoutController@update')   ->name('order.update');
    Route::post('/{order}/pay', 'CheckoutController@pay')->name('payment');
    Route::get('/payment/{payment}/pay', 'CheckoutController@bill')->name('pay');
});

Route::name('userarea.')->prefix('userarea')->middleware(['phone', 'auth', 'verified'])->group(function() {
    Route::get('/', 'UserAreaController@index');
    Route::get('/orders', 'UserAreaController@orders')->name('orders');
    Route::get('/invoices', 'UserAreaController@invoices')->name('invoices');
    Route::get('/invoices/{invoice}', 'UserAreaController@invoice')->name('invoices.show');
    Route::get('/payments', 'UserAreaController@payments')->name('payments');
    Route::get('/payments/{payment}', 'UserAreaController@payment')->name('payment');
    Route::get('/customer', 'UserAreaController@customer')->name('customer');
    Route::post('/customer', 'UserAreaController@store')->name('customercreate');
    Route::post('/customer/{customer}', 'UserAreaController@update')->name('customeredit');
    Route::get('/user/edit', 'UserController@edit')->name('user.edit');
    Route::put('/user/update', 'UserController@update')->name('user.update');
});

Route::prefix('phone')->name('phone.')->group(function() {
   Route::get('verify', 'SMSController@sendVerification')->name('verify');
   Route::post('verify', 'SMSController@verifyCode')->name('verify');
   Route::post('verify/resend', 'SMSController@resendVerification')->name('resend-verify');
});

Route::get('gallery/main-gallery', 'GalleryController@index')->name('gallery.index');

Route::get('gallery/{gallery}', 'GalleryController@show')->name('gallery.show');

Route::prefix('form')->name('form.')->group(function() {
   Route::get('/', 'FormController@index');
   Route::post('/', 'FormController@store')->name('store');
});

Route::match(['get', 'post'], 'verify_payment/{gateway}', [
    'uses' => 'GateWaysController@verify',
    'as'   => 'verifypayment',
]);

Route::prefix('sitemaps')->name('sitemaps.')->group(function(){
    Route::get('/sitemaps.xml', 'SitemapsController@index');
    Route::get('/sitemap-{sitemap}.xml', 'SitemapsController@show')->name('show');
});

Auth::routes(['verify' => true]);

Route::prefix('auth/password')->name('auth.passwords.')->group(function(){
    Route::view('reset', 'auth.passwords.reset')->name('create');
    Route::post('reset/{type}', 'PasswordResetController@store')->name('store');
    Route::put('reset', 'PasswordResetController@update')->name('update');
    Route::get('change/{token}', 'PasswordResetController@show')->name('confirm.form');
    Route::post('sms/resend/{token}', 'PasswordResetController@resendSms')->name('resendsms');
    // Route::post('confirm/phone/{phone}', 'PasswordResetController@phoneVerify')->name('confirm.phone');
});

Route::get('search', 'SearchController@index')->name('pages.search');

app/Http/Controllers/UserAreaController.php
<?php

namespace App\Http\Controllers;

use App\Customer;
use App\Payment;
use App\State;
use Illuminate\Http\Request;

class UserAreaController extends Controller
{
    public function __construct()
    {
        $this->middleware('auth');
    }
    public function index()
    {
        $user = auth()->user();
        return view('userarea.index', compact('user'));
    }
    public function store(Request $request)
    {
        $customer = new Customer;
        $customer->first_name = $request->first_name;
        $customer->last_name  = $request->last_name;
        $customer->phone_number = $request->phone_number;
        $customer->postal_code = $request->postal_code;
        $customer->company = ($request->company) ? $request->company : '';
        $customer->city_id = $request->city;
        $customer->address1 = $request->address1;
        $customer->address2 = ($request->address2) ? $request->address2 : '';
        $customer->note = '';
        $user = auth()->user();
        $user->customer()->create($customer->toArray());
        return redirect()->to(route('userarea.customer'));
    }
    public function update(Request $request, Customer $customer)
    {
        $user = auth()->user();
        if ($customer->user_id == $user->id) {
            $customer->first_name = $request->first_name;
            $customer->last_name  = $request->last_name;
            $customer->phone_number = $request->phone_number;
            $customer->postal_code = $request->postal_code;
            $customer->company = ($request->company) ? $request->company : '';
            $customer->city_id = $request->city;
            $customer->address1 = $request->address1;
            $customer->address2 = ($request->address2) ? $request->address2 : '';
            $customer->save();
        }
        return back();
    }
    public function customer()
    {
        $user = auth()->user();
        $user->load('customer.city.state');
        $states = State::all();
        if ($user->customer) {
            $customer = $user->customer;
            $state = State::with('cities')->whereId($customer->city->state->id)->first();
            $cities = $state->cities;
            return view('userarea.customer.show', compact('user', 'customer', 'states', 'cities'));
        } else {
            $state = State::with('cities')->whereId(1)->first();
            $cities = $state->cities;
            return view('userarea.customer.create', compact('user', 'states', 'cities'));
        }
    }
    public function orders()
    {
        $user = auth()->user();
        $user->load('customer.orders.offer');
        if ($user->customer) {
            $customer = $user->customer;
            $orders = $customer->orders;
            return view('userarea.orders', compact('orders'));
        }
        return back();
    }
    public function invoices()
    {
        $user = auth()->user();
        $user->load('customer');
        if ($user->customer) {
            $invoices = \App\Invoice::whereHas("order", function($q) {
                $user = auth()->user();
                $q->where("customer_id", "=", $user->customer->id);
            })->latest()->get();
            $invoices->load(['order', 'payment.method']);
            return view('userarea.invoices', compact('invoices'));
        }
        return back();
    }
    public function payment(Request $request, Payment $payment)
    {
        $payment->load('method', 'invoice.order');
        $data = $request->data;
        return view('userarea.payment', compact('payment', 'data'));
    }
    public function payments()
    {
        $user = auth()->user();
        if ($user->customer) {
            $payments = Payment::whereHas('invoice.order', function($q){
                $user = auth()->user();
                $q->where('customer_id','=',$user->customer->id);
            })->get();
            $payments->load('method');
            return view('userarea.payments', compact('payments'));
        }
        return route('userarea.');
    }
}

resources/views/userarea/edit.blade.php
@extends('layout.userarea')

@section('head')
    <title>اطلاعات کاربری</title>
    <link rel="stylesheet" href="{{ asset('css/select2.css') }}">
@endsection

@section('dashboardcontent')
<h3 class="col-12 mb-4 float-left">اطلاعات حساب کاربری</h3>
<form action="{{ route('userarea.user.update') }}" class="col-12 mt-4 float-left" method="post">
    @csrf
    @method('PUT')
    <div class="input-group col-12 col-sm-6 offset-sm-6 float-right mb-4">
        <div class="input-group-prepend">
            <span class="input-group-text"><i class="fa fa-user"></i></span>
        </div>
        <input disabled type="text" class="form-control" id="username" value="{{ $user->identification }}">
    </div>
    <h4 class="col-12 text-right mb-2">تغییر رمز عبور : </h4>
    <p class="col-12 text-right">رمز عبور جدید را در کادر زیر وارد کرده و سپس در کادر بعدی آنرا تایید کنید و برروی تغییر کلیک کنید</p>
    <div class="input-group col-12 mt-4 col-sm-6 float-right mb-4">
        <div class="input-group-prepend">
            <span class="input-group-text"><i class="fa fa-lock"></i></span>
        </div>
        <input required type="password" autocomplete="false" class="form-control" name="new_password" id="new_password"
        value="{{ old('new_password') }}" placeholder="رمز عبور جدید">
    </div>
    <div class="input-group col-12 mt-4 col-sm-6 float-right mb-4">
        <div class="input-group-prepend">
            <span class="input-group-text">2<i class="mr-1 fa fa-lock"></i></span>
        </div>
        <input required type="password" class="form-control" name="password_confirm" id="password_confirm"
        value="{{ old('password_confirm') }}" placeholder="تایید رمز عبور">
    </div>
    <div class="input-group col-12 mt-4 col-sm-6 text-center float-right mb-4">
        <button type="submit" class="btn btn-primary">تغییر رمزعبور</button>
    </div>
</form>
@endsection

resources/views/userarea/index.blade.php
@extends('layout.userarea')

@section('head')
    <title>ناحیه کاربری</title>
@endsection

@section('dashboardcontent')
<h3>{{ auth()->user()->name }} عزیز خوش آمدید !</h3>
@endsection

resources/views/userarea/invoice.blade.php
@extends('layout.userarea')

@section('head')
    <title>رسید</title>
@endsection

@section('dashboardcontent')
<div class="title-row float-left">
    <h4 class="title">رسید ها ({{ $invoices->count() }}) :</h4>
    <span class="underline col-sm-2 offset-sm-5 col-8 offset-2 mt-3"></span>
</div>
<table class="table text-center">
    <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">مبلغ(تومان)</th>
            <th scope="col">پرداخت شده</th>
            <th scope="col">روش پرداخت</th>
            <th scope="col">مشاهده سفارش</th>
            <th scope="col">پرداخت</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($invoices as $invoice)
        <tr title="{{ $invoice->status_notes }}">
            <th scope="row">{{ $loop->index + 1 }}</th>
            <td>{{ number_format($invoice->payment->amount) }}</td>
            <td>{!! ifPaid($invoice->payment->paid) !!}</td>
            <td>{{ $invoice->payment->method->name }}</td>
            <td><a href="{{ route('checkout.order', ['order' => $invoice->order->id]) }}" class="btn btn-sm btn-outline-info"><i class="fa fa-eye"></i></a></td>
            <td>
                @if ($invoice->payment->paid)
                ---
                @else
                <form action="{{ route('checkout.pay', ['payment' => $invoice->payment->id]) }}" method="get">
                    <button class="btn btn-sm btn-primary" type="submit"><i class="fa fa-credit-card"></i></button>
                </form>
                @endif
            </td>
            {{-- <td><a href="#" class="btn btn-sm btn-outline-danger"><i class="fa fa-times"></i></a></td> --}}
        </tr>
        @endforeach
    </tbody>
</table>
@endsection

resources/views/userarea/invoices.blade.php
@extends('layout.userarea')

@section('head')
    <title>ناحیه کاربری - رسید ها</title>
@endsection

@section('dashboardcontent')
<div class="title-row float-left">
    <h4 class="title">رسید ها ({{ $invoices->count() }}) :</h4>
    <span class="underline col-sm-2 offset-sm-5 col-8 offset-2 mt-3"></span>
</div>
<table class="table text-center">
    <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">مبلغ(تومان)</th>
            <th scope="col">پرداخت شده</th>
            <th scope="col">روش پرداخت</th>
            <th scope="col">مشاهده سفارش</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($invoices as $invoice)
        <tr title="{{ $invoice->status_notes }}">
            <th scope="row">{{ $invoice->payment->created_at->diffForHumans() }}</th>
            <td>{{ number_format($invoice->payment->amount) }}</td>
            <td>
                {!! ifPaid($invoice->payment->paid) !!}
                @if (! $invoice->payment->paid)
                <form action="{{ route('checkout.pay', ['payment' => $invoice->payment->id]) }}" method="get">
                    <button class="btn btn-sm btn-primary" type="submit">پرداخت<i class="fa fa-credit-card mr-2"></i></button>
                </form>
                @endif
            </td>
            <td>{{ $invoice->payment->method->title }}</td>
            <td><a href="{{ route('checkout.order', ['order' => $invoice->order->id]) }}" class="btn btn-sm btn-outline-info"><i class="fa fa-eye"></i></a></td>
            {{-- <td><a href="#" class="btn btn-sm btn-outline-danger"><i class="fa fa-times"></i></a></td> --}}
        </tr>
        @endforeach
    </tbody>
</table>
@endsection

resources/views/userarea/order.blade.php
@extends('layout.userarea')

@section('head')
    <title>ناحیه کاربری - مشاهده سفارش شماره ({{ $order->id  }})</title>
    <link rel="stylesheet" href="{{ asset('css/select2.css') }}">
@endsection

@php
    $totalWithTax = ($order->total / 100) * 9;
    $all_offer = 0;
@endphp

@section('dashboardcontent')
<h6>سفارش شماره ({{ $order->id }})</h6>
<table class="table table-bordered text-center">
    <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">عنوان</th>
            <th scope="col">تعداد</th>
            <th scope="col">قیمت واحد</th>
            <th scope="col">مجموع</th>
            <th scope="col">تخفیف</th>
            <th scope="col">مجموع پس از کسر</th>
        </tr>
    </thead>
    <tbody class="order-body">
        @foreach ($order->items as $item)
        <tr>
            <th scope="row">{{ $loop->index + 1 }}</th>
            <td>{{ $item->product->title }}</td>
            <td>{{ $item->quantity }}</td>
            <td>{{ number_format($item->product->price) }}</td>
            <td>{{ number_format($item->product->price * $item->quantity) }}</td>
            <td>{{ $item->offer_amount ? number_format($item->offer_amount) : '%' . zeroIfNull($item->product->off) }}</td>
            <td>{{ $item->offer_amount ? number_format(($item->product->price * $item->quantity) - $item->offer_amount) : number_format($item->product->offer() * $item->quantity) }}</td>
        </tr>
        @php $all_offer += $item->offer_amount ?: 0; @endphp
        @endforeach
        <tr>
            <td></td>
            <td>9% مالیات ارزش افزوده</td>
            <td>---</td>
            <td>---</td>
            <td>{{ number_format($totalWithTax) }}</td>
            <td>---</td>
            <td>{{ number_format($totalWithTax) }}</td>
        </tr>
        @php
            $post_price = 0;
        @endphp
        @if ($order->invoice && $order->invoice->shipping_method_id)
            @php
                $shipping_method = \App\Method::whereId($order->invoice->shipping_method_id)->first();
                $post_price = $shipping_method->price;
            @endphp
            <tr id='shipping-pricing'>
                <td></td>
                <td>هزینه ارسال</td>
                <td>---</td>
                <td>---</td>
                <td>{{ number_format($post_price) }}</td>
                <td>---</td>
                <td>{{ number_format($post_price) }}</td>
            </tr>
        @endif
        <tr class="col-12">
            <td></td>
            <th scope="row">مجموع کل</th>
            <td>{{ $order->total_number }}</td>
            <td></td>
            @php
                $totalforDiscount = $order->total + $totalWithTax + $post_price;
                $discounted = $order->discount($totalforDiscount);
                $totalAtAll = $totalforDiscount - $discounted;
            @endphp
            <td>{{ number_format($totalforDiscount + $all_offer) }}</td>
            <th style="direction: ltr;color: red;">{{ number_format(($all_offer) * -1 ) }}</th>
            <td>{{ number_format($totalforDiscount) }}</td>
            @if($order->offer_id)<td class="text-danger" style="direction:ltr;"><b>{{ $discounted * -1 }}</b></td>@endif
            <th>{{ number_format($totalAtAll) }} تومان</th>
        </tr>
    </tbody>
</table>
@if (! $order->invoice)
<div class="col-12 p-3 text-left float-left">
    <form action="{{ route('checkout.payment', ['order' => $order->id]) }}" method="post">
        @csrf
        <div class="payment-methods m-3">
            @include('userarea.components.offer_code')
            @include('userarea.components.payment_method')
            @include('userarea.components.shippment_method')
        </div>
        <div class="col-12 mt-4 float-left text-center">
            <button type="submit" id="pay-btn" class="btn btn-dark cart" href="{{ route('checkout.makeorder') }}"
            data-amount="{{ $totalforDiscount }}"
            >پرداخت</button>
        </div>
    </form>
</div>
@else
<div class="col-12 p-3 text-center float-left">
    <h6>وضعیت پرداخت : {{ ! $order->invoice->payment->paid ? null : $order->invoice->payment->updated_at->diffForHumans() }} {!! ifPaid($order->invoice->payment->paid) !!}</h6>
    @if (! $order->invoice->payment->paid)
        <a href="{{ route('checkout.pay', ['payment' => $order->invoice->payment->id]) }}" class="btn btn-dark">پرداخت</a>
    @else
        @component('userarea.components.reciever', ['order' => $order, 'customer' => $customer]) @endcomponent
    @endif
</div>
@endif
@endsection
@section('script')
<script>

$('#states,#cities').select2();

var Total = {{ $totalAtAll }};
var Total1 = {{ $totalforDiscount + $all_offer }};
var TotalWithoutOff = {{ $totalforDiscount }}

$('.priceable').on('click', function() {
    let price = Number($(this).attr('data-price'));
    let amount = Total + price;
    let amountwithoutoffer = TotalWithoutOff + price
    let amountbefore = Total1 + price;
    console.log(amount);
    $('.order-body > tr:last-child > td:nth-child(5)').html(amountbefore.toLocaleString('en'));
    $('.order-body > tr:last-child > td:nth-child(7)').html(amountwithoutoffer.toLocaleString('en'));
    $('.order-body > tr:last-child > th:last-child').html(amount.toLocaleString('en') + 'تومان ');
    var lasttr = $('.order-body > tr:last-child').html();
    console.log(lasttr);
    $('.order-body > tr:last').remove();
    $('#shipping-pricing').remove();
    let newtr = `<tr id='shipping-pricing'>
        <td></td>
        <td>هزینه ارسال</td>
        <td>---</td>
        <td>---</td>
        <td>${price.toLocaleString('en')}</td>
        <td>---</td>
        <td>${price.toLocaleString('en')}</td>
    </tr>`;
    $('.order-body').append(newtr);
    $('.order-body').append(`<tr>${lasttr}</tr>`);
});

$('#use_customer').on('click', function() {
    $('#recivient_data').toggleClass('d-none');
});

$(document).ready(function() {
    $(document).on('select2:select', '#states', function (e) {
        let stateid = e.params.data.id;
        let http = $(this).attr('data-target');
        axios.get(`${http}/api/state/${stateid}/cities`)
        .then(function (response) {
            let {data} = response;
            $("#cities").html('');
            data.forEach(state => {
                $("#cities").append(`<option value="${state.id}">${state.name}</option>`);
            });
            $('#states').select2();
        });
    });
    $('#shipping-data-button').on('click', function(e) {
        e.preventDefault();
        if (! $('#use_customer').is(':checked')) {
            $('#recivient_data input,textarea,select').each(function(e) {
                // console.log(this);
                $(this).attr('name', $(this).attr('data-name'));
            });
        } else {
            $('#recivient_data input,textarea,select').each(function() {
                $(this).attr('name', null);
            });
        }
        $('#shipping-data-form').submit();
    });
    $('#offer-verification').click(function() {
        let offer_code = $('#offer-code').val();
        let http = $(this).attr('data-api');
        axios.get(`${http}?total_passed=${Total}&offer_code=${offer_code}`).then(res => {
            let {offer, offerId} = res.data;
            if (offerId) {
                $('#off-summary').html("این سفارش با کد ورودی شامل " + offer + 'تومان تخفیف خواهد شد ')
                http = $('#offer-submit').attr('data-api');
                $('#offer-submit').attr('disabled', false).attr('data-api', http.replace('offerId', offerId));
                $('#offer-submit').focus();
            }
        });
    });
    $('#offer-submit').click(function() {
        let http = $(this).attr('data-api');
        axios.post(http).then(res => {
            let {okay, redirect} = res.data;
            if(okay) {
                window.location.href = redirect;
            }
        });
    });
    $('#offer-dismiss').click(function() {
        let http = $('#offer-submit').attr('data-api');
        http = http.replace('offerId', $('#offer-submit').attr('data-current'));
        axios.post(http, {dismiss: true}).then(res => {
            let {okay, redirect} = res.data;
            if(okay) {
                window.location.href = redirect;
            }
        });
    });
});

</script>
@endsection

resources/views/userarea/orders.blade.php
@extends('layout.userarea')

@section('head')
    <title>ناحیه کاربری - سفارش ها</title>
@endsection

@section('dashboardcontent')
<div class="title-row float-left">
    <h4 class="title">سفارش ها ({{ $orders->count() }}) :</h4>
    <span class="underline col-sm-2 offset-sm-5 col-8 offset-2 mt-3"></span>
</div>
<table class="table text-center">
    <thead class="thead-dark">
        <tr>
            <th scope="col">#</th>
            <th scope="col">کد سفارش</th>
            <th scope="col">تعداد کل</th>
            <th scope="col">جمع (تومان)</th>
            <th scope="col">تخفیف</th>
            <th scope="col">پرداختی (تومان)</th>
            <th scope="col">جزئیات</th>
            {{-- <th scope="col">حذف</th> --}}
        </tr>
    </thead>
    <tbody>
        @foreach ($orders as $order)
        <tr class="@if($order->status == "NOTPAID") notpaid @endif" title="{{ $order->status_notes }}">
            <th scope="row">{{ $loop->index + 1 }}</th>
            <td>{{ $order->id }}</td>
            <td>{{ $order->total_number }}</td>
            <td>{{ number_format($order->total) }}</td>
            <td>
                @if ($order->offer)
                {{ $order->offer->amount }} {{ $order->offer->type }}
                @else
                <i class="fa fa-1x fa-times"></i>
                @endif
            </td>
            <td>{{ number_format($order->total) }}</td>
            <td><a href="{{ route('checkout.order', ['order' => $order->id]) }}" class="btn btn-sm btn-outline-info"><i class="fa fa-eye"></i></a></td>
            {{-- <td><a href="#" class="btn btn-sm btn-outline-danger"><i class="fa fa-times"></i></a></td> --}}
        </tr>
        @endforeach
    </tbody>
</table>
@endsection

resources/views/userarea/payment.blade.php
@extends('layout.userarea')

@section('head')
    <title>ناحیه کاربری - مشاهده پرداخت شماره {{ $payment->id }}</title>
@endsection

@section('dashboardcontent')
<h3 class="col-12">پرداخت شماره {{ $payment->id }}# - <span id="counter">5</span></h3>
<table class="table text-center">
    <thead class="thead-dark">
        <tr>
            <th scope="col">وضعیت</th>
            <th scope="col">مبلغ</th>
            <th scope="col">روش پرداخت</th>
            <th scope="col">زمان پرداخت</th>
            <th scope="col">کد تراکنش</th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>{!! ifPaid($payment->paid) !!}</td>
            <td>{{ number_format($payment->amount) }}</td>
            <td>{{ $payment->method->name }}</td>
            <td>{{ $payment->updated_at->diffForHumans() }}</td>
            <td>{{ $payment->RefID }}</td>
            {{-- <td><a href="#" class="btn btn-sm btn-outline-danger"><i class="fa fa-times"></i></a></td> --}}
        </tr>
    </tbody>
</table>
@if ($data)
<script>
    var seconds = 5;
    const intb = window.setInterval(function() {
        seconds -= 1;
        $('#counter').html(seconds);
    }, 1000);
    window.setTimeout(function() {
        window.clearInterval(intb);
        window.location.href = "{{ route('checkout.order', ['order' => $payment->invoice->order->id]) }}"
    }, seconds * 1000)
</script>
@endif
@endsection

resources/views/userarea/payments.blade.php
@extends('layout.userarea')

@section('head')
    <title>ناحیه کاربری - مشاهده پرداخت ها</title>
@endsection

@section('dashboardcontent')
<h3 class="col-12">پرداختی ها</h3>
<table class="table text-center">
    <thead class="thead-dark">
        <tr>
            <th scope="col">ردیف</th>
            <th scope="col">وضعیت</th>
            <th scope="col">مبلغ</th>
            <th scope="col">روش پرداخت</th>
            <th scope="col">زمان پرداخت</th>
            <th scope="col">کد تراکنش</th>
        </tr>
    </thead>
    <tbody>
        @foreach ($payments as $payment)
        <tr>
            <th scope="row">{{ $loop->index + 1 }}</th>
            <td>{!! ifPaid($payment->paid) !!}</td>
            <td>{{ number_format($payment->amount) }}</td>
            <td>{{ $payment->method->title }}</td>
            <td>{{ $payment->updated_at->diffForHumans() }}</td>
            <td>{{ $payment->RefID }}</td>
            {{-- <td><a href="#" class="btn btn-sm btn-outline-danger"><i class="fa fa-times"></i></a></td> --}}
        </tr>
        @endforeach
    </tbody>
</table>
@endsection