routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//

use App\Brand;
use App\Product;
use Illuminate\Http\Request;

Route::get('/', function () {
    $products = Product::with('categories.maincategory')->inRandomOrder()->paginate(12); // with('categories')->
    $products->load('photos.file');
    $products2 = Product::with('categories.maincategory')->latest()->paginate(12); // with('categories')->
    $products2->load('photos.file');
    $brands = Brand::with('photo.file')->get();
    return view('theme.page', compact('products', 'products2', 'brands'));
})->name('home');


Route::name('shop.')->prefix('shop')->group(function(){
    Route::get('/', 'ShopController@index');
    Route::get('/product/{product}', 'ShopController@showProduct')->name('product');
    Route::get('/tag/{tag}/products', 'ShopController@showProductByTag')->name('tag');
    Route::get('/brand/{brand}/products', 'ShopController@showProductByBrand')->name('brand');
    Route::get('/category/{category}', 'ShopController@categorize')->name('category');
});

Route::view('about', 'theme.about')->name('about');

Route::view('contact', 'theme.contact')->name('contact');


Route::name('cart.')->prefix('cart')->group(function(){
    Route::get('/', 'CartController@showCart');
    Route::get('/empty', 'CartController@forgetCart')->name('forget');
    Route::get('/{product}/{action}', 'CartController@cartAction')->name('actions');
});

Route::name('checkout.')->middleware('auth')->prefix('checkout')->group(function() {
    Route::get('/', 'CheckoutController@index')         ->name('makeorder');
    Route::get('/{order}', 'CheckoutController@show')   ->name('order');
    Route::put('/{order}', 'CheckoutController@update')   ->name('order.update');
    Route::post('/{order}/pay', 'CheckoutController@pay')->name('payment');
    Route::get('/payment/{payment}/pay', 'CheckoutController@bill')->name('pay');
});

Route::name('userarea.')->prefix('userarea')->middleware(['phone', 'auth', 'verified'])->group(function() {
    Route::get('/', 'UserAreaController@index');
    Route::get('/orders', 'UserAreaController@orders')->name('orders');
    Route::get('/invoices', 'UserAreaController@invoices')->name('invoices');
    Route::get('/invoices/{invoice}', 'UserAreaController@invoice')->name('invoices.show');
    Route::get('/payments', 'UserAreaController@payments')->name('payments');
    Route::get('/payments/{payment}', 'UserAreaController@payment')->name('payment');
    Route::get('/customer', 'UserAreaController@customer')->name('customer');
    Route::post('/customer', 'UserAreaController@store')->name('customercreate');
    Route::post('/customer/{customer}', 'UserAreaController@update')->name('customeredit');
    Route::get('/user/edit', 'UserController@edit')->name('user.edit');
    Route::put('/user/update', 'UserController@update')->name('user.update');
});

Route::prefix('phone')->name('phone.')->group(function() {
   Route::get('verify', 'SMSController@sendVerification')->name('verify');
   Route::post('verify', 'SMSController@verifyCode')->name('verify');
   Route::post('verify/resend', 'SMSController@resendVerification')->name('resend-verify');
});

Route::get('gallery/main-gallery', 'GalleryController@index')->name('gallery.index');

Route::get('gallery/{gallery}', 'GalleryController@show')->name('gallery.show');

Route::prefix('form')->name('form.')->group(function() {
   Route::get('/', 'FormController@index');
   Route::post('/', 'FormController@store')->name('store');
});

Route::match(['get', 'post'], 'verify_payment/{gateway}', [
    'uses' => 'GateWaysController@verify',
    'as'   => 'verifypayment',
]);

Route::prefix('sitemaps')->name('sitemaps.')->group(function(){
    Route::get('/sitemaps.xml', 'SitemapsController@index');
    Route::get('/sitemap-{sitemap}.xml', 'SitemapsController@show')->name('show');
});

Auth::routes(['verify' => true]);

Route::prefix('auth/password')->name('auth.passwords.')->group(function(){
    Route::view('reset', 'auth.passwords.reset')->name('create');
    Route::post('reset/{type}', 'PasswordResetController@store')->name('store');
    Route::put('reset', 'PasswordResetController@update')->name('update');
    Route::get('change/{token}', 'PasswordResetController@show')->name('confirm.form');
    Route::post('sms/resend/{token}', 'PasswordResetController@resendSms')->name('resendsms');
    // Route::post('confirm/phone/{phone}', 'PasswordResetController@phoneVerify')->name('confirm.phone');
});

Route::get('search', 'SearchController@index')->name('pages.search');

app/Http/Controllers/ShopController.php
<?php

namespace App\Http\Controllers;

use App\Brand;
use App\MainCategory;
use App\Product;
use App\Tag;
use Illuminate\Http\Request;

class ShopController extends Controller
{
    public function index()
    {
        $categories = MainCategory::whereType('product')->get();
        $tags = Tag::whereType('product')->get();
        $brands = Brand::all();
        return view('theme.shop.index', compact('categories', 'tags', 'brands'))->with('target_url', route('api.shop.products.index'));
    }
    public function categorize($category)
    {
        $categories = MainCategory::whereType('product')->get();
        $tags = Tag::all();
        $brands = Brand::all();
        return view('theme.shop.index', compact('categories', 'tags', 'brands'))->with('target_url', route('api.shop.products.category', ['category' => $category]));
    }
    public function showProduct($product)
    {
        $product = Product::whereSlug($product)->firstOrFail();
        $product->load(['photos.file', 'brand', 'categories']);
        return view('theme.shop.show', compact('product'));
    }
    public function showProductByTag($tag)
    {
        $categories = MainCategory::whereType('product')->get();
        $tags = Tag::all();
        $brands = Brand::all();
        return view('theme.shop.index', compact('categories', 'tags', 'brands'))->with('target_url', route('api.shop.products.tag', ['tag' => $tag]));
    }
    public function showProductByBrand($brand)
    {
        $categories = MainCategory::whereType('product')->get();
        $tags = Tag::all();
        $brands = Brand::all();
        return view('theme.shop.index', compact('categories', 'tags', 'brands'))->with('target_url', route('api.shop.products.brand', ['brand' => $brand]));
    }
}

resources/views/theme/shop/cart.blade.php
@extends('layout.shop')
@section('breadcrumb')
{{-- <li class="breadcrumb-item"><a href="{{ route('home') }}">خانه</a></li> --}}
<li class="breadcrumb-item p-0"><a href="{{ route('shop.') }}">فروشگاه</a></li>
<li class="breadcrumb-item active" aria-current="page">سبد خرید</li>
@endsection
@section('shop-content')
<div class="content col-12 p-3" style="min-height:500px;">
    <div class="cart col-12">
        @if ($cart && count($cart->items) > 0)
        <div class="title-row float-left">
            <h4 class="title">سبد خرید ({{ count($cart->items) }}) :</h4>
            <span class="underline col-sm-2 offset-sm-5 col-8 offset-2 mt-3"></span>
        </div>
        <table class="table text-center">
            <thead class="thead-dark">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">عنوان</th>
                    <th scope="col">تعداد</th>
                    <th scope="col">قیمت واحد</th>
                    <th scope="col">مجموع</th>
                    <th scope="col">تخفیف</th>
                    <th scope="col">مجموع پس از کسر</th>
                </tr>
            </thead>
            <tbody>
                @foreach ($cart->items as $item)
                <tr>
                    <th scope="row">{{ $loop->index + 1 }}</th>
                    <td>{{ $item['item']->title }}</td>
                    <td>
                        <a href="{{ route('cart.actions', ['product' => $item['item']->id, 'action' => 'remove']) }}" class="badge badge-secondary"><i class="fa fa-minus"></i></a>
                        {{ $item['quantity'] }}
                        <a href="{{ route('cart.actions', ['product' => $item['item']->id, 'action' => 'add']) }}" class="badge badge-secondary"><i class="fa fa-plus"></i></a>
                    </td>
                    <td>{{ $item['item']->price }}</td>
                    <td>{{ $item['price'] }}</td>
                    <td>%{{ zeroIfNull($item['item']->off) }}</td>
                    <td>{{ $item['item']->offer() * $item['quantity'] }}</td>
                </tr>
                @endforeach
                <tr>
                    <th scope="row">مجموع : </th>
                    <td>---</td>
                    <td>{{ $cart->totalQuantity }}</td>
                    <td>---</td>
                    <td>{{ $cart->totalPrice }}</td>
                    <td>---</td>
                    <td>{{ $cart->totalPay }}</td>
                </tr>
            </tbody>
        </table>
        <div class="col-12 text-left float-left">
            <a class="btn btn-primary cart" href="{{ route('checkout.makeorder') }}">نهایی کردن</a>
            <a class="btn btn-danger cart" href="{{ route('cart.forget') }}"><i class="fa fa-trash"></i> خالی کردن سبد</a>
        </div>
        @else
        <div class="title-row float-left">
            <h4 class="title alert alert-danger">سبد خرید شما خالی است</h4>
        </div>
        @endif
    </div>
</div>
@endsection

resources/views/theme/shop/index.blade.php
@extends('layout.shop')

@section('head')
<title>روبیوتی | فروشگاه</title>
@endsection

@section('breadcrumb')
<li class="breadcrumb-item active" aria-current="page">فروشگاه</li>
@endsection
@section('shop-content')
    <div class="col-md-9 col-12 float-left shopbar p-3 pt-0">
        <div id="react-product-section" data-target="{{ $target_url }}"></div>
    </div>
    <div class="col-md-3 col-12 float-left sidebar p-4">
        <div class="part category-part">
            <p class="title">دسته بندی ها</p>
            <ul class="categories">
                @if ($categories)
                    @foreach ($categories as $category)
                    <li class="cat-item">
                        <a
                        href="{{ route('shop.category', ['category' => $category->name]) }}">
                        {{ $category->name }}
                        <span class="badge badge-light">{{ $category->categories()->count() }}</span>
                        </a>
                        </li>
                    @endforeach
                @else
                <p>دسته بندی موجود نمی باشد</p>
                @endif
            </ul>
        </div>
        {{-- <div class="part price-part">
            <p class="title">قیمت</p>
            <form action="{{ route('shop.') }}" method="get">
                <div class="price-slider">
                    <div class="sliders col-12">
                        <input type="range" name="minprice" class="pricechange col-12 float-left" min="0"
                        step="1000" max="100000" value="1000">
                        <input type="range" name="minprice" class="pricechange col-12 float-left" min="0"
                        step="1000" max="100000" value="100000">
                    </div>
                    <div class="info col-12">

                    </div>
                </div>
            </form>
        </div> --}}
        <div class="part category-part">
            <p class="title">برند</p>
            <ul class="categories">
                @if ($categories)
                    @foreach ($brands as $brand)
                    <li class="cat-item">
                        <a
                        href="{{ route('shop.brand', ['brand' => $brand->name]) }}">
                        {{ $brand->name }}
                        <span class="badge badge-light">{{ $brand->products()->count() }}</span>
                        </a>
                        </li>
                    @endforeach
                @else
                <p>هیچ برندی موجود نمی باشد</p>
                @endif
            </ul>
        </div>
        <div class="part">
            <p class="title">برچسب ها</p>
            <div class="col-12 float-left p-0">
                @if ($tags)
                    @foreach ($tags as $tag)
                    <a class="btn btn-sm btn-outline-primary float-right m-2"
                    href="{{ route('shop.tag', ['tag' => $tag->name]) }}">
                    {{ str_replace('-', ' ',$tag->name) }} ({{ $tag->products()->count() }})
                    </a>
                    @endforeach
                @else
                <p>برچسبی موجود نمی باشد</p>
                @endif
            </div>
        </div>
    </div>
@endsection
@section('scriptcode')
<script>
var VisitProduct  = "{{ route('shop.product', ['product' => 'slug']) }}";
var VisitCategory = "{{ route('shop.category', ['category' => 'categoryName']) }}";
var CartAction = "{{ route('cart.actions', ['product' => 'productId', 'action' => 'actionName']) }}";
var Asset      = "{{ asset('/') }}";
</script>
<script src="{{ asset('js/products.js') }}"></script>
@endsection

resources/views/theme/shop/show.blade.php
@extends('layout.shop')

@section('head')
<title>{{ $product->title }} | فروشگاه روبیوتی</title>
@endsection

@section('breadcrumb')
<li class="breadcrumb-item p-0"><a href="{{ route('shop.') }}">فروشگاه</a></li>
<li class="breadcrumb-item active">{{ $product->title }}</li>
@endsection
@section('shop-content')
    <!-- Swiper -->
    <div class="product-slider col-md-4 p-0 float-right col-12">
        <div class="sliders-container col-12">
            <div class="swiper-container gallery-top">
                <div class="swiper-wrapper">
                @foreach ($product->photos as $photo)
                    <div class="swiper-slide top"><img src="{{ asset($photo->file->path) }}" alt=""></div>
                @endforeach
                </div>
                <!-- Add Arrows -->
                <div class="swiper-button-next swiper-button-white"></div>
                <div class="swiper-button-prev swiper-button-white"></div>
            </div>
            @if (count($product->photos) > 1)
                <div class="swiper-container gallery-thumbs">
                    <div class="swiper-wrapper">
                    @foreach ($product->photos as $photo)
                        <div class="swiper-slide thumb"><img src="{{ asset($photo->file->path) }}" alt=""></div>
                    @endforeach
                    </div>
                </div>
            @endif
        </div>
    </div>
    <div class="pr-section col-md-8 pl-0 col-12">
        <div class='product-info-container col-md-9 col-12'>
            <h1 class='product-name'>{{ $product->title }}</h1>
            <div class="col-12 float-left text-right">
                <div class="float-right ml-2">
                    @if ($product->quantity > 0)
                        <span class="badge badge-success">{{ $product->quantity }} عدد موجود است</span>
                    @else
                        <span class="badge badge-danger">ناموجود</span>
                    @endif
                </div>
                <div class="product-info ml-2">
                    <p>برند : <a href="{{ route('shop.brand', ['brand' => $product->brand->name]) }}">
                    <span>{{ $product->brand->name }}</span>
                    </a></p>
                </div>
                <div class="product-info">
                    <p> دسته بندی :
                    @foreach ($product->categories as $category)
                        <span>{{ $category->name }}</span>
                    @endforeach </p>
                </div>
            </div>
            <div class="product-properties">
                <div class="col-12 col-md-6 float-right persian">
                    <h5>ویژگی های محصول</h5>
                    <p>{{ $product->short_description }}</p>
                </div>
                <div class="col-12 col-md-6 float-right text-left" style="direction: ltr;">
                    {!! $product->english_description !!}
                </div>
            </div>
            <p class="price-section text-right float-left col-12">{!! $product->displayPrice() !!}</p>
            <br/>
            <div class="col-12 mt-4 float-left text-center">
                @if ($product->quantity > 0)
                <a href="{{ route('cart.actions', ['product' => $product->id, 'action' => 'add']) }}" class='btn btn-dark btn-large'>افزودن به سبد خرید <i class="fa fa-shopping-cart"></i></a>
                @else
                <button disabled type="button" class="btn btn-dark btn-large">در انبار موجود نیست</button>
                @endif
            </div>
        </div>
        {{-- <div class="buy-section-container col-md-5 col-12">
            <ul>
                <li>گارانتی اصالت و سلامتی فیزیکی کالا</li>
                <li>زیر قیمت بازار</li>
                <li>آماده ارسال</li>
                <li>بهترین کیفیت</li>
            </ul>

            <br/>
        </div> --}}
    </div>
    <div class="pro-desc col-12 float-left p-3">
        <div class="card text-center col-12 p-0 float-right">
            <div class="card-header bg-dark">
                <ul class="nav nav-tabs card-header-tabs">
                    <li class="nav-item">
                        <a class="nav-link active" href="#">توضیحات</a>
                    </li>
                </ul>
            </div>
            <div class="card-body">
                <article class="col-12 text-right float-right p-3">
                    {!! $product->description !!}
                </article>
            </div>
        </div>
    </div>
@endsection

@section('scriptcode')
<!-- Initialize Swiper -->
<script>
    var galleryThumbs = new Swiper.default('.gallery-thumbs', {
    spaceBetween: 10,
    slidesPerView: 3,
    loop: true,
    freeMode: true,
    loopedSlides: 5, //looped slides should be the same
    watchSlidesVisibility: true,
    watchSlidesProgress: true,
    });
    var galleryTop = new Swiper.default('.gallery-top', {
    spaceBetween: 10,
    loop:true,
    slidesPerView: 1,
    loopedSlides: 5, //looped slides should be the same
    navigation: {
        nextEl: '.swiper-button-next',
        prevEl: '.swiper-button-prev',
    },
    thumbs: {
        swiper: galleryThumbs,
    },
    });</script>
@endsection